<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('settings')->insert([
            [
                'id' => 1,
                'key' => 'site_name',
                'value' => 'NOBI FASHION Việt Nam',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 2,
                'key' => 'site_description',
                'value' => 'NOBI FASHION mang đến thời trang nam trẻ trung, thanh lịch và cá tính. Bộ sưu tập áo, quần, phụ kiện hot trend [NOBI]currentyear[NOBI], giá hợp lý, mua ngay!',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 3,
                'key' => 'site_logo',
                'value' => 'setting-site_logo-1757497205.png',
                'type' => 'image',
                'group' => 'general',
                'label' => 'Ảnh Logo',
                'description' => NULL,
                'is_public' => 1,
                'is_required' => 1,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-09-10 09:40:05',
            ],
            [
                'id' => 4,
                'key' => 'site_announcement',
                'value' => 'MIỄN PHÍ VẬN CHUYỂN VỚI ĐƠN HÀNG NỘI THÀNH > 300K - ĐỔI TRẢ TRONG 30 NGÀY - ĐẢM BẢO CHẤT LƯỢNG',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 5,
                'key' => 'site_favicon',
                'value' => 'setting-site_favicon-1758009788.png',
                'type' => 'image',
                'group' => 'general',
                'label' => 'Favicon chính',
                'description' => NULL,
                'is_public' => 1,
                'is_required' => 1,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-09-16 08:03:08',
            ],
            [
                'id' => 6,
                'key' => 'contact_email',
                'value' => 'support@nobifashion.vn',
                'type' => 'email',
                'group' => 'general',
                'label' => 'Email hỗ trợ',
                'description' => NULL,
                'is_public' => 1,
                'is_required' => 1,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-09-10 10:00:38',
            ],
            [
                'id' => 7,
                'key' => 'contact_phone',
                'value' => '0827786198',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Số điện thoại Đức Nobi 💖',
                'description' => NULL,
                'is_public' => 1,
                'is_required' => 1,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-09-10 10:12:31',
            ],
            [
                'id' => 8,
                'key' => 'contact_address',
                'value' => 'chợ Đôn, Hải Phòng, Việt Nam',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 9,
                'key' => 'seo_keywords',
                'value' => 'NOBI FASHION, NOBI FASHION Hải Phòng, cửa hàng NOBI FASHION, shop NOBI FASHION, shop thời trang NOBI FASHION, quần áo NOBI FASHION, quần áo nam nữ NOBI FASHION, thời trang giá rẻ NOBI FASHION, NOBI FASHION khuyến mãi, địa chỉ NOBI FASHION Hải Phòng, siêu thị mini NOBI FASHION, cửa hàng mini NOBI FASHION, cửa hàng tiện lợi NOBI FASHION, mua sắm NOBI FASHION, mua sắm giá rẻ NOBI FASHION, đồ dùng gia đình NOBI FASHION, đồ gia dụng NOBI FASHION, cửa hàng đồ gia dụng NOBI FASHION, phụ kiện tiện ích NOBI FASHION, phụ kiện thời trang NOBI FASHION, áo nam NOBI FASHION, áo nữ NOBI FASHION, quần nam NOBI FASHION, quần nữ NOBI FASHION, outfit NOBI FASHION Hải Phòng, NOBI FASHION chính hãng',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Keywords chính - Trang chủ',
                'description' => NULL,
                'is_public' => 1,
                'is_required' => 1,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-09-10 10:06:46',
            ],
            [
                'id' => 10,
                'key' => 'seo_author',
                'value' => 'Nguyễn Minh Đức (Đức Nobi)',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 11,
                'key' => 'facebook_link',
                'value' => 'https://www.facebook.com/ducnobi2004',
                'type' => 'url',
                'group' => 'general',
                'label' => 'Facebook Đức Nobi',
                'description' => NULL,
                'is_public' => 1,
                'is_required' => 1,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-09-10 09:51:01',
            ],
            [
                'id' => 12,
                'key' => 'twitter_link',
                'value' => 'https://twitter.com/',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 13,
                'key' => 'google_analytics',
                'value' => '',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 14,
                'key' => 'enable_registration',
                'value' => 'true',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 15,
                'key' => 'enable_comments',
                'value' => 'true',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 16,
                'key' => 'enable_newsletter',
                'value' => 'true',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 17,
                'key' => 'site_timezone',
                'value' => 'Asia/Ho_Chi_Minh',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 18,
                'key' => 'site_language',
                'value' => 'vi',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 19,
                'key' => 'enable_ssl',
                'value' => 'true',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 20,
                'key' => 'maintenance_mode',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'general',
                'label' => 'Chế độ bảo trì',
                'description' => NULL,
                'is_public' => 1,
                'is_required' => 1,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-09-10 10:07:44',
            ],
            [
                'id' => 21,
                'key' => 'copyright',
                'value' => '<p>Copyright &copy; {{ ((2025 != now()->year & 2025 < now()->year) ? \'2025 - \' : \'\'). now()->year }} <a style=\"color: green;\" href=\"{{ $settings[\'site_url\'] }}\">{{ $settings[\'site_name\'] }}</a>. All Rights Reserved.</p>',
                'type' => 'textarea',
                'group' => 'general',
                'label' => 'Copyright Footer',
                'description' => NULL,
                'is_public' => 1,
                'is_required' => 1,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-09-10 10:09:08',
            ],
            [
                'id' => 22,
                'key' => 'contact_form_recipient',
                'value' => 'contact@nobifashion.vn',
                'type' => 'email',
                'group' => 'general',
                'label' => 'Email nhận thông tin',
                'description' => NULL,
                'is_public' => 1,
                'is_required' => 1,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-09-10 10:03:47',
            ],
            [
                'id' => 23,
                'key' => 'allow_file_uploads',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'general',
                'label' => 'Cho phép tải lên FILE',
                'description' => 'Cho phép tải lên FILE',
                'is_public' => 1,
                'is_required' => 1,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-09-10 09:43:04',
            ],
            [
                'id' => 24,
                'key' => 'site_url',
                'value' => 'https://nobifashion.vn',
                'type' => 'url',
                'group' => 'general',
                'label' => 'Domain',
                'description' => NULL,
                'is_public' => 1,
                'is_required' => 1,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-09-10 09:54:44',
            ],
            [
                'id' => 25,
                'key' => 'site_slug',
                'value' => '/',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 26,
                'key' => 'site_title',
                'value' => 'NOBI FASHION – Shop Quần Áo Nam Nữ Đẹp, Mix & Match Chuẩn Gu',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Meta title - Trang chủ',
                'description' => NULL,
                'is_public' => 1,
                'is_required' => 1,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-09-10 10:05:42',
            ],
            [
                'id' => 27,
                'key' => 'google_search_console',
                'value' => '',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 28,
                'key' => 'instagram_link',
                'value' => 'https://www.facebook.com/ducnobi2004',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 29,
                'key' => 'dmca',
                'value' => '',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 30,
                'key' => 'dmca_logo',
                'value' => '',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 31,
                'key' => 'bo_cong_thuong',
                'value' => 'setting-bo_cong_thuong-1757497818.webp',
                'type' => 'image',
                'group' => 'general',
                'label' => 'Ảnh bộ công thương',
                'description' => NULL,
                'is_public' => 1,
                'is_required' => 1,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-09-10 09:50:18',
            ],
            [
                'id' => 32,
                'key' => 'contact_zalo',
                'value' => '0398951396',
                'type' => 'text',
                'group' => 'general',
                'label' => 'Zalo Đức Nobi 💖',
                'description' => NULL,
                'is_public' => 1,
                'is_required' => 1,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-09-10 10:11:52',
            ],
            [
                'id' => 33,
                'key' => 'telegram_link',
                'value' => '1',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 34,
                'key' => 'discord_link',
                'value' => '1',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 35,
                'key' => 'site_image',
                'value' => '',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 36,
                'key' => 'google_tag_header',
                'value' => '\n<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':\nnew Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],\nj=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\n\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);\n})(window,document,\'script\',\'dataLayer\',\'GTM-KPTC863L\');</script>\n\n\n<script async src=\"https://www.googletagmanager.com/gtag/js?id=AW-17013569193\">\n</script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag(\'js\', new Date());\n\n  gtag(\'config\', \'AW-17013569193\');\n</script>\n\n<script>\n  gtag(\'event\', \'conversion\', {\n      \'send_to\': \'AW-17013569193/3VCDCPK1zrkaEKnt2bA_\',\n      \'value\': 1.0,\n      \'currency\': \'VND\'\n  });\n</script>\n',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 37,
                'key' => 'google_tag_body',
                'value' => '\n<noscript><iframe src=\"https://www.googletagmanager.com/ns.html?id=GTM-KPTC863L\"\nheight=\"0\" width=\"0\" style=\"display:none;visibility:hidden\"></iframe></noscript>\n',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 38,
                'key' => 'site_pinterest',
                'value' => '',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 39,
                'key' => 'site_banner',
                'value' => 'banner.webp',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 40,
                'key' => 'url_banner',
                'value' => 'setting-url_banner-1757498296.png',
                'type' => 'image',
                'group' => 'general',
                'label' => 'Banner chính',
                'description' => NULL,
                'is_public' => 1,
                'is_required' => 1,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-09-10 09:58:16',
            ],
            [
                'id' => 41,
                'key' => 'bing_tag_header',
                'value' => '',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 06:10:59',
                'updated_at' => '2025-06-11 06:10:59',
            ],
            [
                'id' => 45,
                'key' => 'city',
                'value' => 'Hải Phòng',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-07-16 16:46:33',
                'updated_at' => NULL,
            ],
            [
                'id' => 43,
                'key' => 'postalCode',
                'value' => '180000',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-11 14:31:16',
                'updated_at' => NULL,
            ],
            [
                'id' => 44,
                'key' => 'subname',
                'value' => 'NOBI FASHION Việt Nam',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-06-16 14:23:46',
                'updated_at' => NULL,
            ],
            [
                'id' => 46,
                'key' => 'district',
                'value' => 'QUẬN KIẾN AN',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-07-16 16:47:28',
                'updated_at' => NULL,
            ],
            [
                'id' => 47,
                'key' => 'ward',
                'value' => 'PHƯỜNG LÃM HÀ',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-07-16 16:47:28',
                'updated_at' => NULL,
            ],
            [
                'id' => 48,
                'key' => 'detail_address',
                'value' => '20/58 phố Đoàn Kết',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-07-16 16:47:28',
                'updated_at' => NULL,
            ],
            [
                'id' => 49,
                'key' => 'latitude',
                'value' => '20.83943',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-07-20 15:55:34',
                'updated_at' => NULL,
            ],
            [
                'id' => 50,
                'key' => 'longitude',
                'value' => '106.65338',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-07-20 15:55:34',
                'updated_at' => NULL,
            ],
            [
                'id' => 51,
                'key' => 'enable_cart',
                'value' => 'true',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-07-22 03:54:49',
                'updated_at' => NULL,
            ],
            [
                'id' => 52,
                'key' => 'enable_order',
                'value' => 'true',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-07-22 03:54:49',
                'updated_at' => NULL,
            ],
            [
                'id' => 53,
                'key' => 'enable_payment',
                'value' => 'true',
                'type' => 'text',
                'group' => 'general',
                'label' => '',
                'description' => NULL,
                'is_public' => 0,
                'is_required' => 0,
                'created_at' => '2025-07-22 03:57:43',
                'updated_at' => NULL,
            ],
        ]);
    }
}

// php artisan db:seed --class=SettingsTableSeeder